spring:
  application:
    name: card
  h2:
    console:
      enabled: true
  datasource:
    username: admin
    password: ""
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  profiles:
    active: prod

  config:
    import: "optional:configserver:http://localhost:8071/"
#  optional:configserver:http://localhost:8071/ where the configuration is not so important

server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

  endpoint:
    shutdown:
      enabled: true

    health:
      probes:
        enabled: true

  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/


info:
  app:
    name: "card"
    description: "Eazy Bank Card Application"
    version: "1.0.0"

logging:
  level:
    com:
      eazybytes:
        card: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

