build:
  version: "2,0"
loan:
  message: "Welcome to EazyBank Loan related local APIs in QA Environment"
  contactDetails:
    name: "Jame Paul - QA Lead"
    email: "jamespaul@eazybank.com"
  onCallSupport:
    - (599) 555-1274
    - (399) 523-1365
