spring:
  application:
    name: configserver
  profiles:
    active: git
  #    active: native  -when reading from local system
  cloud:
    config:
      server:
        #        native:  when reading from local system
        #          search-locations: file:///Users//Uexcel//eazybytes//config
        #          search-locations: "classpath:/config"  - reading from class path
        git:
          uri: "https://github.com/Uexcel2022/config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  Key: E1gH3kUxLzN3i9JVzL6hEP7VBaTgF

server:
  port: 8071

